name: ChildrenOfTheWorld
favicon: null
layout_spectrum: 0.83211
typography_spectrum: 0.7333656165283173
title: "Sex, Drugs, Rock & Roll: Photography from the 70's"
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f3f2f7'
    - '#999594'
    - '#666563'
    - '#121212'
    - '#bfbcbd'
  brandStrength: 1
  lightness: 0.5
  saturation: 0.6875
  rhythmicContrast: 0.25
purpose: []
