name: ChildrenOfTheWorld
favicon: null
layout_spectrum: 0.83211
typography_spectrum: 0.7333656165283173
title: "Sex, Drugs, Rock & Roll: Photography from the 70's"
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#130a06'
    - '#c7a79f'
    - '#815c5b'
    - '#9d8588'
    - '#4e6275'
  brandStrength: 0
  lightness: 0.4375
  saturation: 0.6875
  rhythmicContrast: 0.5
purpose: []
